In [ ]:
DATA FRAMES

In [2]:
import numpy as np 
import pandas as pd

In [3]:
#creating a data frame==================================

In [4]:
data = {
    "Name": ["John", "Michel", "Sara", "Liam"],
    "City": ["New York", "Paris", "London", "Toronto"],
    "Age": [25, 30, 22, 28],
    "Occupation": ["Engineer", "Designer", "Doctor", "Developer"]
}
df1 = pd.DataFrame(data)
df1

     Name      City  Age Occupation
0    John  New York   25   Engineer
1  Michel     Paris   30   Designer
2    Sara    London   22     Doctor
3    Liam   Toronto   28  Developer

In [5]:
data_list = [
    ["John", 25, "New York", "Engineer"],
    ["Michel", 30, "Paris", "Designer"],
    ["Sara", 22, "London", "Doctor"],
    ["Liam", 28, "Toronto", "Developer"]
]
column = ["Name", "Age", "City", "Occupation"]
df2 = pd.DataFrame(data_list, columns= column, index=range(1,len(data_list)+1))
df2

     Name  Age      City Occupation
1    John   25  New York   Engineer
2  Michel   30     Paris   Designer
3    Sara   22    London     Doctor
4    Liam   28   Toronto  Developer

In [6]:
#Selection and indexing of columns ==================================

In [7]:
df2['Name']

1      John
2    Michel
3      Sara
4      Liam
Name: Name, dtype: object

In [8]:
df2['City']

1    New York
2       Paris
3      London
4     Toronto
Name: City, dtype: object

In [9]:
df2[['Name', 'City']]

     Name      City
1    John  New York
2  Michel     Paris
3    Sara    London
4    Liam   Toronto

In [10]:
#Creating a new column ==================================

In [11]:
df2['Salaries']= [75000, 68000, 82000, 91000]

In [12]:
df2

     Name  Age      City Occupation  Salaries
1    John   25  New York   Engineer     75000
2  Michel   30     Paris   Designer     68000
3    Sara   22    London     Doctor     82000
4    Liam   28   Toronto  Developer     91000

In [13]:
#Removing column ==================================

In [14]:
df2.drop('Salaries', axis= 1)    # it will only show copy after droping column, it will not remove the column from database.

     Name  Age      City Occupation
1    John   25  New York   Engineer
2  Michel   30     Paris   Designer
3    Sara   22    London     Doctor
4    Liam   28   Toronto  Developer

In [15]:
df2.drop('Salaries', axis= 1, inplace=True) # to remove it from column too you have to use inplace keyword

In [16]:
# we can remove multiple column by giving list of items to drop in the drop command

In [17]:
#Rmoving rows ===================================

In [18]:
df2.drop( 1,axis= 0 )  # we have to give label and axis = 0 (it is by defalut)

     Name  Age     City Occupation
2  Michel   30    Paris   Designer
3    Sara   22   London     Doctor
4    Liam   28  Toronto  Developer

In [19]:
df2

     Name  Age      City Occupation
1    John   25  New York   Engineer
2  Michel   30     Paris   Designer
3    Sara   22    London     Doctor
4    Liam   28   Toronto  Developer

In [20]:
#Selecting Rows ===================================

In [21]:
df2.loc[1]  #This is to access rows data by giving lable

Name              John
Age                 25
City          New York
Occupation    Engineer
Name: 1, dtype: object

In [22]:
df2.loc[[1,2]]  # this is for acessing multiple rows

     Name  Age      City Occupation
1    John   25  New York   Engineer
2  Michel   30     Paris   Designer

In [23]:
df2.iloc[0] # this is used when lables are different, not labels of  index values

Name              John
Age                 25
City          New York
Occupation    Engineer
Name: 1, dtype: object

In [24]:
#Selecing subsets of rows and column =====================================

In [25]:
df2

     Name  Age      City Occupation
1    John   25  New York   Engineer
2  Michel   30     Paris   Designer
3    Sara   22    London     Doctor
4    Liam   28   Toronto  Developer

In [26]:
df2.iloc[[0,1]][['City', 'Occupation']]

       City Occupation
1  New York   Engineer
2     Paris   Designer

In [27]:
df2.iloc[[2,3]][['Name', 'Age']]

   Name  Age
3  Sara   22
4  Liam   28

In [28]:
#Conditional Selection

In [29]:
df2

     Name  Age      City Occupation
1    John   25  New York   Engineer
2  Michel   30     Paris   Designer
3    Sara   22    London     Doctor
4    Liam   28   Toronto  Developer

In [30]:
#Q i want to see details of those who are above 25

In [31]:
df2[df2['Age']>25]

     Name  Age     City Occupation
2  Michel   30    Paris   Designer
4    Liam   28  Toronto  Developer

In [32]:
#q i want to see details of those who are above 25 and from paris

In [33]:
df2[(df2['Age']>25) & (df2['City'] =='Paris')]

     Name  Age   City Occupation
2  Michel   30  Paris   Designer