In [2]:
import numpy as np 
import pandas as pd

In [19]:
#Finding missing values

In [44]:
import numpy as np

# Example dictionary for missing data concept
data = {
    "Name": [ "Bhavya",np.nan, "Chirag", np.nan, "Divya", "Esha", np.nan],
    "Age": [18, 19, np.nan, 20, np.nan, 21, 22],
    "Marks": [85, np.nan, 90, 88, np.nan, 92, 80],
    "City": ["Delhi", np.nan, "Mumbai", np.nan, "Bangalore", np.nan, "Kolkata"]
}
df = pd.DataFrame(data)
df

     Name   Age  Marks       City
0  Bhavya  18.0   85.0      Delhi
1     NaN  19.0    NaN        NaN
2  Chirag   NaN   90.0     Mumbai
3     NaN  20.0   88.0        NaN
4   Divya   NaN    NaN  Bangalore
5    Esha  21.0   92.0        NaN
6     NaN  22.0   80.0    Kolkata

In [45]:
df.isna()  # It checks the none values and returns true where none value exists

    Name    Age  Marks   City
0  False  False  False  False
1   True  False   True   True
2  False   True  False  False
3   True  False  False   True
4  False   True   True  False
5  False  False  False   True
6   True  False  False  False

In [46]:
df.isna().sum()  #it counts the number of null values  column wise

Name     3
Age      2
Marks    2
City     3
dtype: int64

In [47]:
df.isna().any()  # this returns flase if any column has no null values

Name     True
Age      True
Marks    True
City     True
dtype: bool

In [48]:
#Removing null values  (it works on the basis of rows )

In [49]:
df

     Name   Age  Marks       City
0  Bhavya  18.0   85.0      Delhi
1     NaN  19.0    NaN        NaN
2  Chirag   NaN   90.0     Mumbai
3     NaN  20.0   88.0        NaN
4   Divya   NaN    NaN  Bangalore
5    Esha  21.0   92.0        NaN
6     NaN  22.0   80.0    Kolkata

In [50]:
df.dropna()  # it will remove all the rows except the rows which doesn't have null value in it

     Name   Age  Marks   City
0  Bhavya  18.0   85.0  Delhi

In [51]:
df

     Name   Age  Marks       City
0  Bhavya  18.0   85.0      Delhi
1     NaN  19.0    NaN        NaN
2  Chirag   NaN   90.0     Mumbai
3     NaN  20.0   88.0        NaN
4   Divya   NaN    NaN  Bangalore
5    Esha  21.0   92.0        NaN
6     NaN  22.0   80.0    Kolkata

In [52]:
df.dropna(thresh=3) # it will remove the rows which doesn't have minimum 3 real values

     Name   Age  Marks     City
0  Bhavya  18.0   85.0    Delhi
2  Chirag   NaN   90.0   Mumbai
5    Esha  21.0   92.0      NaN
6     NaN  22.0   80.0  Kolkata

In [53]:
#Filling the missing data

In [54]:
df

     Name   Age  Marks       City
0  Bhavya  18.0   85.0      Delhi
1     NaN  19.0    NaN        NaN
2  Chirag   NaN   90.0     Mumbai
3     NaN  20.0   88.0        NaN
4   Divya   NaN    NaN  Bangalore
5    Esha  21.0   92.0        NaN
6     NaN  22.0   80.0    Kolkata

In [56]:
df.fillna(0)  # This will fill the null value places with a given value (column wise selection )

     Name   Age  Marks       City
0  Bhavya  18.0   85.0      Delhi
1       0  19.0    0.0          0
2  Chirag   0.0   90.0     Mumbai
3       0  20.0   88.0          0
4   Divya   0.0    0.0  Bangalore
5    Esha  21.0   92.0          0
6       0  22.0   80.0    Kolkata

In [66]:
values = {'Name':'xyz', 'Age':'19', 'Marks': 33, 'City': 'Delhi' }

In [68]:
df.fillna(value= values)# This is to fill a particular column with a specific value (column wise selection )

     Name   Age  Marks       City
0  Bhavya  18.0   85.0      Delhi
1     xyz  19.0   33.0      Delhi
2  Chirag    19   90.0     Mumbai
3     xyz  20.0   88.0      Delhi
4   Divya    19   33.0  Bangalore
5    Esha  21.0   92.0      Delhi
6     xyz  22.0   80.0    Kolkata

In [69]:
df

     Name   Age  Marks       City
0  Bhavya  18.0   85.0      Delhi
1     NaN  19.0    NaN        NaN
2  Chirag   NaN   90.0     Mumbai
3     NaN  20.0   88.0        NaN
4   Divya   NaN    NaN  Bangalore
5    Esha  21.0   92.0        NaN
6     NaN  22.0   80.0    Kolkata