In [6]:
import numpy as np
import pandas as pd

**MERGING TWO DATA FRAMES**

In [10]:
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 27, 22]
})

df2 = pd.DataFrame({
    'ID': [1, 2, 4],
    'City': ['New York', 'Los Angeles', 'Chicago'],
    'Country': ['USA', 'USA', 'USA']
})

df1

   ID     Name  Age
0   1    Alice   24
1   2      Bob   27
2   3  Charlie   22

In [11]:
df2

   ID         City Country
0   1     New York     USA
1   2  Los Angeles     USA
2   4      Chicago     USA

In [14]:
pd.merge(df1,df2, on = 'ID', how= 'inner')
# 'on' defines the common column used to match rows (ID in this case)
# 'how="inner"' returns only the rows where IDs are present in both DataFrames

   ID   Name  Age         City Country
0   1  Alice   24     New York     USA
1   2    Bob   27  Los Angeles     USA

In [15]:
pd.merge(df1,df2, on = 'ID', how= 'outer')
# 'on' specifies the common column used for merging (ID here)
# 'how="outer"' returns all rows from both DataFrames, matching where possible and filling missing values with NaN

   ID     Name   Age         City Country
0   1    Alice  24.0     New York     USA
1   2      Bob  27.0  Los Angeles     USA
2   3  Charlie  22.0          NaN     NaN
3   4      NaN   NaN      Chicago     USA

In [18]:
# 'on' tells which common column to use for merging (ID here)
# 'how="left"' keeps all rows from df1 an

   ID     Name  Age         City Country
0   1    Alice   24     New York     USA
1   2      Bob   27  Los Angeles     USA
2   3  Charlie   22          NaN     NaN

In [19]:
pd.merge(df1,df2, on = 'ID', how= 'right') 
# 'on' specifies the common column used for joining (here it's 'ID')
# 'how="right"' keeps all rows from df2 and only matching rows from df1

   ID   Name   Age         City Country
0   1  Alice  24.0     New York     USA
1   2    Bob  27.0  Los Angeles     USA
2   4    NaN   NaN      Chicago     USA

**CONCATINATION OF TWO DATA FRAMES**

In [24]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3'],
    'C': ['C0', 'C1', 'C2', 'C3']
})

df2 = pd.DataFrame({
    'A': ['A4', 'A5', 'A6', 'A7'],
    'B': ['B4', 'B5', 'B6', 'B7'],
    'C': ['C4', 'C5', 'C6', 'C7']
})
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

In [25]:
df2

    A   B   C
0  A4  B4  C4
1  A5  B5  C5
2  A6  B6  C6
3  A7  B7  C7

In [30]:
pd.concat([df1, df2]) 
# This stacks df2 below df1 (row-wise) without changing original DataFrames

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
0  A4  B4  C4
1  A5  B5  C5
2  A6  B6  C6
3  A7  B7  C7

In [32]:
pd.concat([df2, df1]) 
# This stacks df1 below df2 (row-wise) without changing original DataFrames

    A   B   C
0  A4  B4  C4
1  A5  B5  C5
2  A6  B6  C6
3  A7  B7  C7
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

In [33]:
pd.concat([df1, df2], axis = 1)  
# Joins df1 and df2 side-by-side (column-wise), matching rows by index

    A   B   C   A   B   C
0  A0  B0  C0  A4  B4  C4
1  A1  B1  C1  A5  B5  C5
2  A2  B2  C2  A6  B6  C6
3  A3  B3  C3  A7  B7  C7

**JOINING OF 2 DATA FRAMES**

In [39]:
df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David']
}, index = [1, 2, 3, 4])
df2 = pd.DataFrame({
    'Score': [80, 85, 90, 95]
}, index = [ 2, 3, 4, 5])
df1

      Name
1    Alice
2      Bob
3  Charlie
4    David

In [40]:
df2

   Score
2     80
3     85
4     90
5     95

In [42]:
df1.join(df2) 
# inner join which joins df2 in df1 and the df2 does not conatain 1 so in place of score of 1st one there is NaN is produced as output 
# it contain only df1 items and the same id items from df2 table like here from score data frame the 5 is not joined 
# and here i written df1 first so the df1's column is printed first

      Name  Score
1    Alice    NaN
2      Bob   80.0
3  Charlie   85.0
4    David   90.0

In [44]:
df2.join(df1)
#here 1 is not joined because i joining df1 in df2

   Score     Name
2     80      Bob
3     85  Charlie
4     90    David
5     95      NaN

In [43]:
df1.join(df2, how= 'outer') 
# Here both the data frames items are merged and in 1st one's score and 5th ones name there is NaN

      Name  Score
1    Alice    NaN
2      Bob   80.0
3  Charlie   85.0
4    David   90.0
5      NaN   95.0