In [41]:
import numpy as np 
import pandas as pd

**GROUP BY**

In [42]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store':    ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales':    [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date':     pd.date_range('2023-01-01', periods=8)
}

df = pd.DataFrame(data)

In [43]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [44]:
# Group by Category and calculate the sum of sales

In [45]:
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [46]:
# Group by Store and calculate the sum of sales

In [47]:
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [48]:
#Group by multiple culumns 
#Group by Catogery and Store

In [49]:
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

**AGGREGATION**

In [50]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store':    ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales':    [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date':     pd.date_range('2023-01-01', periods=8)
}

df = pd.DataFrame(data)

In [51]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [56]:
df['Sales'].mean()

np.float64(187.5)

In [57]:
#Other functions like : median, min, max, count, std

In [55]:
df['Sales'].std()

66.06274074155351

In [60]:
df['Sales'].agg(['mean', 'median', 'min', 'max', 'count', 'std'])

mean      187.500000
median    190.000000
min       100.000000
max       300.000000
count       8.000000
std        66.062741
Name: Sales, dtype: float64

In [61]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64